import assert from 'node:assert/strict';
import test from 'node:test';
import {blankStore,publish,startSession,answerSession,submitSession,decodeStore,newRound,addFinding,makeReport,saveStore} from '../src/lib/trial/model.ts';
import {appendBehavior,behaviorIsActive,retryBehavior,selectedEvidence,consentBehavior,behaviorMessage,behaviorComparable,geometryKey,behaviorSummary,SIMULATION_LAYOUT,type BehaviorEvent} from '../src/lib/trial/behavior.ts';
const setup=()=>{const store=publish({...blankStore(),projects:[{id:'p',name:'QA',goal:'trial'}],tests:[{id:'t',projectId:'p',title:'Test',draft:{testId:'t',title:'Test',url:'https://example.com',target:{kind:'simulation',layoutVersion:SIMULATION_LAYOUT},tasks:[{id:'task',instruction:'Read'}]}}]},'t');return startSession(store,store.versions[0].id);};
const event=(s:ReturnType<typeof setup>):BehaviorEvent=>({id:'event',sessionId:s.session.id,versionId:s.store.versions[0].id,taskId:'task',sequence:1,at:new Date().toISOString(),type:'pointer',screenId:'houses',layoutVersion:SIMULATION_LAYOUT,viewportWidth:390,viewportHeight:600,documentWidth:390,documentHeight:960,documentX:80,documentY:800,elementId:'houses-house18'});
test('consent and active task are enforced; refresh persists exact event and duplicates do not count',()=>{const s=setup(),e=event(s);assert.throws(()=>appendBehavior(s.store,e));const store=appendBehavior(consentBehavior(s.store,s.session.id),e);assert.equal(appendBehavior(store,e),store);assert.equal(decodeStore(JSON.stringify(store)).behaviorEvents?.length,1);assert.throws(()=>appendBehavior(store,{...e,id:'other'}),/ลำดับ/);assert.throws(()=>appendBehavior(store,{...e,documentX:90}),/ไม่ตรง/);const answered=answerSession(store,s.session.id,{taskId:'task',outcome:'done',ease:null,feedback:''});assert.throws(()=>appendBehavior(answered,{...e,id:'late',sequence:2}));assert.throws(()=>appendBehavior(submitSession(answered,s.session.id),{...e,id:'late',sequence:2}));});
test('bridge requires exact origin/window and never copies typed values; keyboard has no coordinates',()=>{const s=setup(),e=event(s),source={};const context={sessionId:e.sessionId,versionId:e.versionId,taskId:e.taskId,sequence:1};const msg={origin:'https://utp.example',source,data:{protocol:'utp:first-party-web',version:1,type:'pointer',data:{...e,x:80,y:200,scrollY:600,inputValue:'SECRET'}}};assert.equal(behaviorMessage({...msg,origin:'https://other.example'},msg.origin,source,context),null);assert.equal(behaviorMessage({...msg,source:{}},msg.origin,source,context),null);const point=behaviorMessage(msg,msg.origin,source,context)!;assert.equal(point.documentY,800);assert.equal(point.scrollY,600);assert.equal('inputValue' in point,false);const key=behaviorMessage({...msg,data:{...msg.data,type:'action'}},msg.origin,source,context)!;assert.equal(key.documentX,undefined);assert.equal(behaviorSummary([key])?.clicks,0);assert.equal(behaviorSummary([key])?.actions,1);assert.equal(behaviorSummary([]),null);assert.equal(behaviorMessage({...msg,data:{...msg.data,data:{...e,documentY:9999}}},msg.origin,source,context),null);});
test('geometry never combines viewport, document dimensions, screen or layout; resize is not a path step',()=>{const s=setup(),e=event(s);for(const change of [{viewportWidth:320},{viewportHeight:700},{documentHeight:980},{screenId:'house18'},{layoutVersion:'other'}])assert.notEqual(geometryKey({...e,...change}),geometryKey(e));const resize={...e,type:'screen_view',documentX:undefined,documentY:undefined,transitionReason:'resize'} as BehaviorEvent;assert.equal(behaviorSummary([resize])?.paths.length,0);});
test('failed local write is not accepted; identical retry succeeds once and stale writes remain blocked',()=>{const s=setup(),e=event(s);let raw=JSON.stringify(consentBehavior(s.store,s.session.id));const storage={getItem:()=>raw,setItem:(_k:string,v:string)=>{raw=v;}};const expected=raw,next=appendBehavior(decodeStore(raw),e);assert.throws(()=>saveStore({...storage,setItem:()=>{throw Error('quota');}},next,expected));assert.equal(decodeStore(raw).behaviorEvents?.length||0,0);const saved=saveStore(storage,next,expected);assert.equal(decodeStore(saved).behaviorEvents?.length,1);assert.throws(()=>saveStore(storage,next,expected));const retry=saveStore(storage,appendBehavior(decodeStore(saved),e),saved);assert.equal(decodeStore(retry).behaviorEvents?.length,1);});
test('evidence references exact submitted session/version/event; report and new round retain snapshots',()=>{const s=setup(),e=event(s);let store=appendBehavior(consentBehavior(s.store,s.session.id),e);const f={id:'f',versionId:e.versionId,problem:'QA',impact:'QA',recommendation:'QA',evidence:[{sessionId:e.sessionId,taskId:e.taskId,kind:'heatmap' as const,eventIds:[e.id]}]};assert.throws(()=>addFinding(store,f));store=submitSession(answerSession(store,s.session.id,{taskId:e.taskId,outcome:'done',ease:null,feedback:''}),s.session.id);assert.throws(()=>addFinding(store,{...f,evidence:[{...f.evidence[0],eventIds:['missing']}]}));assert.throws(()=>addFinding(store,{...f,evidence:[{...f.evidence[0],kind:'path'}]}));store=makeReport(addFinding(store,f),e.versionId);f.evidence[0].eventIds.push('modified');assert.deepEqual(store.reports[0].findings[0].evidence[0].eventIds,[e.id]);assert.equal(decodeStore(JSON.stringify(store)).reports.length,1);const next=publish(newRound(store,e.versionId),'t');assert.equal(behaviorComparable(store.versions[0],next.versions[1]),true);assert.equal(behaviorComparable(store.versions[0],{...next.versions[1],target:undefined}),false);});
test('legacy stores decode; corrupt geometry and duplicate sequences rejected',()=>{assert.deepEqual(decodeStore(JSON.stringify(blankStore())).behaviorEvents,undefined);const s=setup(),e=event(s),store=appendBehavior(consentBehavior(s.store,s.session.id),e);for(const events of [[{...e,documentX:-1}],[e,{...e,id:'duplicate'}]])assert.throws(()=>decodeStore(JSON.stringify({...store,behaviorEvents:events})));});

test('pending retry recovers after another tab accepts the same sequence; replay keeps the canonical ID',()=>{
  const s=setup(),pending=event(s);
  const current=appendBehavior(consentBehavior(s.store,s.session.id),{...pending,id:'other-tab'});
  const next=retryBehavior(current,[pending]);
  assert.equal(next.behaviorEvents?.[1].sequence,2);
  assert.equal(next.behaviorEvents?.[1].id,pending.id);
  assert.equal(retryBehavior(next,[pending]),next);
  assert.throws(()=>retryBehavior(next,[{...pending,documentY:810}]),/ไม่ตรง/);
  const finished=answerSession(next,s.session.id,{taskId:'task',outcome:'done',ease:null,feedback:''});
  assert.equal(behaviorIsActive(finished,pending),false);
  assert.throws(()=>retryBehavior(finished,[{...pending,id:'late'}]));
});
test('untrusted evidence URL is validated; compact report references resolve frozen exact event IDs',()=>{
  const s=setup(),e=event(s);
  let store=appendBehavior(consentBehavior(s.store,s.session.id),e);
  store=submitSession(answerSession(store,s.session.id,{taskId:'task',outcome:'done',ease:null,feedback:''}),s.session.id);
  const evidence={sessionId:e.sessionId,taskId:'task',kind:'heatmap' as const,eventIds:[e.id]};
  store=makeReport(addFinding(store,{id:'finding',versionId:e.versionId,problem:'QA',impact:'QA',recommendation:'QA',evidence:[evidence]}),e.versionId);
  const query=new URLSearchParams({report:store.reports[0].id,fi:'0',ei:'0'});
  assert.deepEqual(selectedEvidence(store,e.versionId,query),evidence);
  assert.equal(selectedEvidence(store,'other-version',query),null);
  assert.equal(selectedEvidence(store,e.versionId,new URLSearchParams({finding:'finding',ei:'0'}))?.kind,'heatmap');
  for(const value of [{eventIds:[],kind:{}}, {...evidence,eventIds:[{}]}, {...evidence,eventIds:['missing']}, {...evidence,kind:'other'}])
    assert.equal(selectedEvidence(store,e.versionId,new URLSearchParams({evidence:JSON.stringify(value)})),null);
  assert.equal(selectedEvidence(store,e.versionId,new URLSearchParams({report:store.reports[0].id,fi:'bad',ei:'0'})),null);
});
