alter table public.users force row level security;
alter table public.workspaces force row level security;
alter table public.workspace_members force row level security;
alter table public.projects force row level security;
alter table public.tests force row level security;
alter table public.test_versions force row level security;
alter table public.tasks force row level security;
alter table public.participants force row level security;
alter table public.sessions force row level security;
alter table public.task_sessions force row level security;
alter table public.events force row level security;
alter table public.answers force row level security;
alter table public.findings force row level security;
alter table public.finding_evidence force row level security;
alter table public.retests force row level security;
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke execute on all functions in schema public from anon;
alter default privileges in schema public revoke all on tables from anon;
alter default privileges in schema public revoke all on sequences from anon;
alter default privileges in schema public revoke execute on functions from public, anon;
revoke all on schema private from public, anon;
revoke execute on all functions in schema private from public, anon;
grant usage on schema private to authenticated, service_role;
grant execute on all functions in schema private to authenticated, service_role;
